body:
  - type: markdown
    attributes:
      value: |
        Start a discussion about some aspect of CF that you think we should consider changing:
        how it could be improved,
        what's wrong with it, what its purposes should be,
        whether it could be managed better, etc.
        Please add one or more of the labels
        `conventions`, `vocabulary` (standard names etc.), `website`, or `governance`,
        to indicate which area of CF the discussion is relevant to,
        by clicking on the cogwheel next to **Labels** on the top right of this form.
        Apply more than one label if it's unclear which is applicable.
        You can also add and remove labels after starting the discussion.
