body:
- type: textarea
  attributes:
    label: Question
    description: |
      Ask a question about some aspect of CF e.g. how to do something, what something means, what standard name to choose, why something isn't working as expected, where to find some information, how to make a suggestion for change. Please add one or more of the labels `conventions`, `vocabulary` (standard names etc.), `website`, `governance` or `GitHub`, to indicate which area of CF the discussion is relevant to, by clicking on the cogwheel :gear: next to **Labels** on the top right of this form. Apply more than one label if it's unclear which is applicable. You can also add and remove labels after starting the discussion.
    placeholder: Type in here. Markdown is supported, and you will be able to preview your text before posting it.
  validations:
    required: true
