blank_issues_enabled: false
contact_links:
  - name: Q&A about using CF
    url: https://github.com/orgs/cf-convention/discussions/new?category=q-a-about-using-cf
    about: Ask a question about how to use any aspect of CF or how it works (conventions, vocabulary, website, governance, GitHub etc.)
  - name: Comments and ideas for changing CF
    url: https://github.com/orgs/cf-convention/discussions/new?category=comments-and-ideas-for-changing-cf
    about: Start a discussions about an improvement to any aspect of CF (conventions, vocabulary, website, governance, GitHub etc.)
