# This workflow comments on issues that have had no activity for a specified amount of time. This is a reminder for the community to comment and for standard name moderators to comment.

name: Comment on stale standard name issues

#thinking this should only run once a month on the 1st day
on:
  schedule:
  - cron: '* * * * 1'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity in the last 21 days. This is a reminder to please comment on standard name requests to assist with agreement and acceptance. Standard name moderators are also reminded to review @japamment @feggleton'
        days-before-stale: 21
        exempt-all-assignees: true
        issue-labels: standard name
